baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'mysite'
theme = 'mytheme'

[params]
  title = "Nivas Pvs"
  subtitle="Subtitle takes some time."

[menu]
[[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes"
    weight = 10 

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = false
  [markup.tableOfContents]
    endlevel = 4
